### ISSUE TITLE
2020 County Precinct-Level Election Results Typos

### ISSUE THREAD

**Issue by peter-redistricting-data-hub** [openelections/openelections-sources-or#11]
Note: I did not check whether these errors are also present in the combined precinct-level election results file.

**1) Baker County:** Baker City 5 05, Jorgensen should have 22 votes, not 2.

Source: https://github.com/openelections/openelections-sources-or/blob/master/2020/general/Baker%20OR%20General.pdf

![Screen Shot 2021-11-16 at 10 25 27 AM](https://user-images.githubusercontent.com/72451074/142014231-f34a1695-3518-4a87-b5bb-966381aba2d4.png)

**2) Wheeler County:** Spray 04: Thatcher should have 229 votes, not 299

https://github.com/openelections/openelections-sources-or/blob/master/2020/general/Wheeler%20OR%20Certified%20Abstract%2011-3-2020.pdf

![Screen Shot 2021-11-16 at 10 27 52 AM](https://user-images.githubusercontent.com/72451074/142014630-2d186cc0-6942-43e4-bc61-704291cfca02.png)

**3) Morrow County:** Ione 04 Jorgensen should have 10 votes not 14 and Hunter should have 4 votes not 0

![Screen Shot 2021-11-16 at 10 37 40 AM](https://user-images.githubusercontent.com/72451074/142016343-d26cd384-fc0a-40d8-9946-c6cf0e6ae769.png)

**4) Grant County:** Long Creek 17 Jorgensen should have 3 votes not 4 and Hunter should have 0 votes not 1, John Day 03 Howie Hawkins should have 8 votes, not 0.

https://github.com/openelections/openelections-sources-or/blob/master/2020/general/Grant%20OR%202020%20General.pdf

**5) Coos County:** Nathalie Paravincini votes are dropped

**6) Marion County:** In the senate races Dye received Taher's votes, Taher recieved Merkley's votes

https://github.com/openelections/openelections-sources-or/blob/master/2020/general/MARION%20OR%20Official%20Canvass%20Results%2011-23-20.pdf

**Comment by dwillis** [comment]
@peter-redistricting-data-hub The Baker County one you reference Baker Precinct 5 but your example circles the 22 votes from Precinct 3, so I think the data there is correct.

**Comment by dwillis** [comment]
@peter-redistricting-data-hub The others are fixed now.

**Comment by peter-redistricting-data-hub** [comment]
![Screen Shot 2021-11-30 at 11 24 33 AM](https://user-images.githubusercontent.com/72451074/144086839-f84b2c61-192b-4fa0-ae66-1356e981f983.png)

Sorry about circling the wrong precinct for Baker County, they both have 22 votes. But I believe the Baker Precinct 5 example is still incorrect

**Comment by peter-redistricting-data-hub** [comment]
Also, from the above, I think you may have skipped correcting the Grant County issue where John Day 03 Howie Hawkins should have 8 votes, not 0.
